## Arquivo values para ambiente de Sandbox
image:
  tag: dev-1b79bbc2

env:
  COLOR: YELLOW

ingress:
  annotations:
    rewrite_target:
      enabled: false
      value: /
    app_root:
      enabled: false
      value:

spec:
  replicas: 1
  resources:
    requests:
      cpu: 0.5
      memory: 300Mi
    limits:
      cpu: 500m
      memory: 1Gi
