name: cicd

on: 
  push: 
    branches: 
      - main

env:
  GITHUB_REPOSITORY_NAME: ${{ github.event.repository.name }}
  GITHUB_SHA: ${{ github.event.pull_request.head.sha }}

jobs: 
  docker-build: 
    runs-on: ubuntu-latest
    steps:
    - name: Inject slug/short variables
      uses: rlespinasse/github-slug-action@v4
    - run: echo ${GITHUB_REPOSITORY}
    - run: echo ${GITHUB_REPOSITORY_NAME_PART}
#    - run: echo ${GITHUB_SERVER_URL}

    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Login Docker Hub
      uses: docker/login-action@v3
      with: 
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        login-server: ${{ secrets.DOCKER_CONTAINER_REGISTRY }}

    - name: Build e Push no Azure Container Registry
      run: |
        echo "commit sha ${GITHUB_SHA}"
        docker build . --file Dockerfile --tag ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/${GITHUB_REPOSITORY_NAME_PART}:latest
        docker tag ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/${GITHUB_REPOSITORY_NAME_PART}:latest ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/${GITHUB_REPOSITORY_NAME_PART}:${GITHUB_SHA_SHORT}
        docker push ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/${GITHUB_REPOSITORY_NAME_PART}:${GITHUB_SHA_SHORT}


#    - name: Build e Push no Azure Container Registry
#      run: |
#        echo "commit sha ${{ GITHUB_SHA }}"
#        docker build . --file Dockerfile --tag ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/${{ env.GITHUB_REPOSITORY_NAME }}:latest
#        docker tag ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/${{ env.GITHUB_REPOSITORY_NAME }}:latest ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/${{ env.GITHUB_REPOSITORY_NAME }}:${{ GITHUB_SHA_SHORT }}
#        docker push ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/${{ env.GITHUB_REPOSITORY_NAME }}:${{ GITHUB_SHA_SHORT }}

  
change-image-tag-helm: git 
  image: 
    name: robertsilvatech/ubuntu-with-git:20.04
    entrypoint: [ '/bin/bash', '-c', 'ln -snf /bin/bash /bin/sh && /bin/bash -c $0' ]
  needs: 
    - docker-build
  stage: change-image-tag
  variables:
    CONFIG_REPO_NAME: gitops-example
    PROJECT_FOLDER: sample-python-application
  before_script:
    - git config --global user.email "deivid@dcpilla.eti.br" && git config --global user.name "Deivid Pilla" 







