name: cicd

on: 
  push: 
    branches: 
      - main

env:
  GITHUB_REPOSITORY_NAME: ${{ github.event.repository.name }}

jobs: 
  docker: 
    runs-on: self-hosted
    steps: 
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Login Docker Hub
      uses: docker/login-action@v3
      with: 
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build e Push no Azure Container Registry
      run: |
        docker build . --file Dockerfile --tag ${{ env.GITHUB_REPOSITORY_NAME }}:${{ GITHUB_SHA_SHORT }}
        docker push ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/${{ env.GITHUB_REPOSITORY_NAME }}:${{ GITHUB_SHA_SHORT }}

  
#  change-helm:



