name: cicd

on: 
  push: 
    branches: 
      - main

env:
  GITHUB_REPOSITORY_NAME: ${{ github.event.repository.name }}
  GITHUB_SHA: ${{ github.event.pull_request.head.sha }}

jobs: 
  docker: 
    runs-on: ubuntu-latest
    steps:
    - name: Inject slug/short variables
      uses: rlespinasse/github-slug-action@v4
    - run: echo ${GITHUB_REPOSITORY}
    - run: echo ${GITHUB_REPOSITORY_NAME_PART}
#    - run: echo ${GITHUB_SERVER_URL}

    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Login Docker Hub
      uses: docker/login-action@v3
      with: 
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        login-server: ${{ secrets.DOCKER_CONTAINER_REGISTRY }}

    - name: Build e Push no Azure Container Registry
      run: |
        echo "commit sha ${GITHUB_SHA}"
        docker build . --file Dockerfile --tag ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/${GITHUB_REPOSITORY_NAME_PART}:latest
        docker tag ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/${GITHUB_REPOSITORY_NAME_PART}:latest ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/${GITHUB_REPOSITORY_NAME_PART}:${GITHUB_SHA_SHORT}
        docker push ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/${GITHUB_REPOSITORY_NAME_PART}:${GITHUB_SHA_SHORT}


#    - name: Build e Push no Azure Container Registry
#      run: |
#        echo "commit sha ${{ GITHUB_SHA }}"
#        docker build . --file Dockerfile --tag ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/${{ env.GITHUB_REPOSITORY_NAME }}:latest
#        docker tag ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/${{ env.GITHUB_REPOSITORY_NAME }}:latest ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/${{ env.GITHUB_REPOSITORY_NAME }}:${{ GITHUB_SHA_SHORT }}
#        docker push ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/${{ env.GITHUB_REPOSITORY_NAME }}:${{ GITHUB_SHA_SHORT }}

  
#  change-helm:




