name: cicd

on: 
  push: 
    branches: 
      - main

env:
  GITHUB_REPOSITORY_NAME: ${{ github.event.repository.name }}
  GITHUB_SHA: ${{ github.event.pull_request.head.sha }}

jobs: 
  docker: 
    runs-on: ubuntu-latest
    steps: 
    - name: Inject slug/short variables
      uses: rlespinasse/github-slug-action@v4
    - run: echo ${GITHUB_REPOSITORY}
    - run: echo ${GITHUB_REPOSITORY_NAME_PART}
  
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Login Docker Hub
      uses: docker/login-action@v3
      with: 
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        login-server: ${{ secrets.DOCKER_CONTAINER_REGISTRY }}

    - name: Build e Push no Azure Container Registry
      run: |
        echo "commit sha ${GITHUB_SHA}"
        docker build . --file Dockerfile --tag ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/${GITHUB_REPOSITORY_NAME_PART}:latest
        docker tag ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/${GITHUB_REPOSITORY_NAME_PART}:latest ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/${GITHUB_REPOSITORY_NAME_PART}:${GITHUB_SHA_SHORT}
        docker push ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/${GITHUB_REPOSITORY_NAME_PART}:${GITHUB_SHA_SHORT}

  
    # 6. Checkout do repositório de configuração do Helm
    - name: Checkout Helm config repo
      uses: actions/checkout@v3
      with:
        repository: https://github.com/dcpilla/gitops-example.git
        path: sample-python-application/helm
        token: ${{ secrets.GIT_TOKEN }}


    # 7. Atualizar a versão da imagem no values.yaml do ambiente correspondente
    - name: Update image version in Helm values
      run: |
        cd helm-config
        ENVIRONMENT="dev"  # Defina o ambiente dinamicamente (ex: usando uma variável de ambiente ou input)
        sed -i "s|image: dcpilla/${GITHUB_REPOSITORY_NAME_PART}:.*|image: dcpilla/${GITHUB_REPOSITORY_NAME_PART}:${GITHUB_SHA_SHORT}|g" values-$ENVIRONMENT.yaml
        git config --global user.name "Deivid Pilla"
        git config --global user.email "deivid@dcpilla.eti.br"
        git add .
        git commit -m "Update image version to ${GITHUB_SHA_SHORT} for $ENVIRONMENT"
        git push
