name: cicd

on: 
  push: 
    branches: 
      - main

env:
  GITHUB_REPOSITORY_NAME: ${{ github.event.repository.name }}
  GITHUB_SHA: ${{ github.event.pull_request.head.sha }}

jobs: 
  docker: 
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Login Docker Hub
      uses: docker/login-action@v3
      with: 
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        login-server: ${{ secrets.DOCKER_CONTAINER_REGISTRY }}

    - name: Build e Push no Azure Container Registry
      run: |
        docker build . --file Dockerfile --tag ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/${{ env.GITHUB_REPOSITORY_NAME }}:latest
        docker tag ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/${{ env.GITHUB_REPOSITORY_NAME }}:latest ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/${{ env.GITHUB_REPOSITORY_NAME }}:${{ env.GITHUB_SHA }}
        docker push ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/${{ env.GITHUB_REPOSITORY_NAME }}:${{ env.GITHUB_SHA }}

  
#  change-helm:




